### ISSUE TITLE
Imports in flat implicit structure fail in #94

### ISSUE THREAD

**Issue by mlstolk** [matrx-software/matrx#107]
In the process of creating a flat implicit reference structure in feature branch #94_flat_implicit_folder_structure_test, commit ID 73a7bf98956200873b5d2f3d100a877af076e9f4, import errors occur for functions in the (classless) utils.py.

**Stacktrace**
```Traceback (most recent call last):
  File "C:/Users/stolkml/OneDrive - TNO/PycharmProjects/matrx/main.py", line 1, in <module>
    from matrx.API import api
  File "C:\Users\stolkml\OneDrive - TNO\PycharmProjects\matrx\matrx\__init__.py", line 12, in <module>
    _module = loader.find_module(module_name).load_module(module_name)
  File "C:\Users\stolkml\OneDrive - TNO\PycharmProjects\matrx\matrx\API\api.py", line 9, in <module>
    from matrx.utils import Message
  File "C:\Users\stolkml\OneDrive - TNO\PycharmProjects\matrx\matrx\utils\__init__.py", line 1, in <module>
    from .utils import *
  File "C:\Users\stolkml\OneDrive - TNO\PycharmProjects\matrx\matrx\utils\utils.py", line 6, in <module>
    from matrx.agents import SenseCapability
  File "C:\Users\stolkml\OneDrive - TNO\PycharmProjects\matrx\matrx\agents\__init__.py", line 2, in <module>
    from .agent_brain import *
  File "C:\Users\stolkml\OneDrive - TNO\PycharmProjects\matrx\matrx\agents\agent_brain.py", line 5, in <module>
    from matrx.actions import GrabObject, OpenDoorAction, CloseDoorAction, RemoveObject
  File "C:\Users\stolkml\OneDrive - TNO\PycharmProjects\matrx\matrx\actions\__init__.py", line 2, in <module>
    from .door_actions import *
  File "C:\Users\stolkml\OneDrive - TNO\PycharmProjects\matrx\matrx\actions\door_actions.py", line 4, in <module>
    from matrx.objects import Door
  File "C:\Users\stolkml\OneDrive - TNO\PycharmProjects\matrx\matrx\objects\__init__.py", line 1, in <module>
    from .env_object import *
  File "C:\Users\stolkml\OneDrive - TNO\PycharmProjects\matrx\matrx\objects\env_object.py", line 1, in <module>
    from matrx.utils import get_default_value, next_obj_id, get_inheritence_path
ImportError: cannot import name 'get_default_value' from 'matrx.utils' (C:\Users\stolkml\OneDrive - TNO\PycharmProjects\matrx\matrx\utils\__init__.py)`

**Comment by jwaa** [comment]
Removed the `defaults.json` file in the scenarios folder. Replaced by a `defaults.py` file filled with some constants. The usage is the same, but now its a pure python file which can only be changed on package level (not on user level as was the original idea of a `defaults.json`).

This may break any projects that rely on the usage of a `defaults.json`. These now have to explicitely provide the intended arguments to the WorldBuild instead.

@mlstolk Can you test if this resolves the issue?

**Comment by jwaa** [comment]
I believe I fixed it now. 
@mlstolk; shall we take a look if it also works for you?

Examples:
```from matrx.actions import Action

from matrx.agents import SenseCapability

from matrx.agents import PatrollingAgent

from matrx import get_distance

from matrx import WorldBuilder

**Comment by thaije** [comment]
@jwaa has this been fixed?

**Comment by jwaa** [comment]
@thaije I believe so, but I asked @mlstolk to test it before I close and merge it.
