### ISSUE TITLE
API exception when retrieving states

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#121]
**Describe the bug**
It seems this a hard bug to spot... I have no clue when it exactly happens. It seems to occur when the API tries to retrieve a state from an agent (human agents for me, but no idea of its specific for them). At this point it tries to search its id in a stored dictionary of states, but the id is nowhere to be found.

**To Reproduce**
No idea when it really happens.

**Expected behavior**
Not flooding my console with exceptions.

**Screenshots**
N/A

**Stacktrace**
```
[2020-03-25 11:16:28,476] ERROR in app: Exception on /get_latest_state_and_messages/['human_69'] [GET]
Traceback (most recent call last):
  File "D:\Utilities\Anaconda3\envs\matrx-dev\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Utilities\Anaconda3\envs\matrx-dev\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Utilities\Anaconda3\envs\matrx-dev\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Utilities\Anaconda3\envs\matrx-dev\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Utilities\Anaconda3\envs\matrx-dev\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Utilities\Anaconda3\envs\matrx-dev\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Utilities\Anaconda3\envs\matrx-dev\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\Projects\MATRX\matrx\api\api.py", line 88, in get_latest_state_and_messages
    states_ = __fetch_states(current_tick, agent_id)
  File "E:\Projects\MATRX\matrx\api\api.py", line 654, in __fetch_states
    states_this_tick[agent_id] = states[t][agent_id]
KeyError: 'human_69'
```

**Additional context**
This occurs for me when running `main.py` and the `vis_test.py`, and most of the time when I have the two human agents and the god view open and sending messages to and from the human agents. Also, it seems to have something to do with pausing the world, but I am not sure if that's it. But I have the feeling that it only occurs when the world is paused through the god view.

**Comment by jwaa** [comment]
Update: It seems just to occur after 2 to 3 minutes for me. 

I run the `vis_test.py`, open the god view and two human agents. Few minutes later; flooded console with exceptions.

**Comment by thaije** [comment]
Fixed in commit https://github.com/matrx-software/matrx/commit/37a3058f2f1bd461d36bfe97e81aff5956d4bbf5. When the API receives a request for a state from a specific agent, first the existence of that agent ID is checked. This thus still gives a message in the terminal from the API when someone tries fetching a non-existent Agent ID, but a small white one instead of a hard red error :)
