### ISSUE TITLE
Refresh agent view on a new world

### ISSUE THREAD

**Issue by jwaa** [matrx-software/matrx#132]
**Describe the bug**
When a new world starts it is possible that the agent IDs change because more or less objects are added to a world due to the `prospect` methods. This causes any browser sessions linking to that agent view to stop working.

**To Reproduce**
Create a world with one agent and one object using the `WorldBuilder.add_object_prospect` method. Set a `LimitedTimeGoal` with a small number of ticks, and loop through a number of worlds. Run this, open a browser, go to the agent view and run the world with the God view.

One can also run the BW4T task, as this contains prospect objects as well.

**Expected behavior**
Either a pop-up saying that this agent is unavailable, or a refresh and link change to the new view which is still linked to the same `AgentBrain`

**Screenshots**
N/A

**Stacktrace**
This also causes the following stacktrace as the `MessageHandler` seems to be unable to handle this situation (trace from the BW4T task):
```
[2020-04-01 15:53:44,083] ERROR in app: Exception on /get_latest_state_and_messages/['human 0 in team 0_157'] [GET]
Traceback (most recent call last):
  File "D:\Utilities\Anaconda3\envs\bw4t\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Utilities\Anaconda3\envs\bw4t\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Utilities\Anaconda3\envs\bw4t\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "D:\Utilities\Anaconda3\envs\bw4t\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Utilities\Anaconda3\envs\bw4t\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\Utilities\Anaconda3\envs\bw4t\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Utilities\Anaconda3\envs\bw4t\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Utilities\Anaconda3\envs\bw4t\lib\site-packages\matrx\api\api.py", line 88, in get_latest_state_and_messages
    states_ = __fetch_states(current_tick, agent_id)
  File "D:\Utilities\Anaconda3\envs\bw4t\lib\site-packages\matrx\api\api.py", line 654, in __fetch_states
    states_this_tick[agent_id] = states[t][agent_id]
KeyError: 'human 0 in team 0_157'
```

**Additional context**
N/A

**Comment by thaije** [comment]
I would counter propose to have a static random seed for the instantiation of obj IDs that does not change for subsequent instances of the same scenario. In that way we don't have the above issue, and it would be substantially less work to implement. Win-win situation? @jwaa what do you think about this?

**Comment by jwaa** [comment]
See #155, which may solve this partially. It would atleast make it easier for people to use the API (since the agent ids are known if they are all named unique), and as an extension also the standard visualisation.

**Comment by thaije** [comment]
With v2.0.7., this has been fixed. Agents always need a unique name, and after fixing issue #155 the object ID is the same as the object name. As such, the url does not change in the frontend, as the obj ID stays the same.
