### ISSUE TITLE
Change agent image size during simulation

### ISSUE THREAD

**Issue by rsverhagen94** [matrx-software/matrx#329]
**What is your question?**
Is it possible to change image size of agents while the simulation is already running? I tried using self.agent_properties, but without success.

**To what is your question related?**
- [ ] I am not sure if I should use MATRX.
- [ ] I have a question about the idea behind MATRX.
- [x] I don't know how to do something with MATRX.
- [ ] I don't know where to find something.
- [ ] I think I found a bug, but I am not sure.
- [ ] I want to contribute, but don't know where to start.
- [ ] Something else.

**Comment by jwaa** [comment]
Hey @rsverhagen94! Adjusting visualization properties on the fly can indeed be a hassle. Can you provide a bit of a code snippet on what you tried with the `self.agent_properties` attribute? Also include where you make the adjustments (i.e., in the `decide_on_action` method).

**Comment by rsverhagen94** [comment]
@jwaa thanks for the quick reply! I tried the following code in the `decide_on_action` method of the agent class:
`self.agent_properties["visualization"]["size"] = 5.0`. When printing `self.agent_properties` it actually shows the changed size, but no differences are visually noticeable in the simulation.

**Comment by jwaa** [comment]
Now a bit later reply, sorry for that. It seems that changing the visualization properties is a bit of as hassle since an update. Could you try this:

```python
self.agent_properties["visualize_size"] = 5.0
```

All of the visualization properties are in their nested dictionaries, but the part that modifies it throughout MATRX cannot handle such nested properties. So the solution MATRX now uses is to translate all of them to `"visualization_<property name>"`. 

Let me know if this works!

**Comment by rsverhagen94** [comment]
> Now a bit later reply, sorry for that. It seems that changing the visualization properties is a bit of as hassle since an update. Could you try this:
> 
> ```python
> self.agent_properties["visualize_size"] = 5.0
> ```
> 
> All of the visualization properties are in their nested dictionaries, but the part that modifies it throughout MATRX cannot handle such nested properties. So the solution MATRX now uses is to translate all of them to `"visualization_<property name>"`.
> 
> Let me know if this works!

This returns the following error:
```python
Traceback (most recent call last):
  File "main.py", line 51, in <module>
    carry_together_case.run(scenario)
  File "/home/ruben/Downloads/moving_out/case/carry_together_case.py", line 196, in run
    world.run(builder.api_info)
  File "/home/ruben/.local/lib/python3.8/site-packages/matrx/grid_world.py", line 246, in run
    is_done, tick_duration = self.__step()
  File "/home/ruben/.local/lib/python3.8/site-packages/matrx/grid_world.py", line 697, in __step
    agent_obj._set_agent_changed_properties(agent_properties)
  File "/home/ruben/.local/lib/python3.8/site-packages/matrx/objects/agent_body.py", line 237, in _set_agent_changed_properties
    raise Exception(f"Agent {self.obj_id} tried to remove the property {prop}, which is not allowed.")
Exception: Agent robot tried to remove the property visualize_size, which is not allowed.
```
When adding the agent using ``builder.add_agent``, I included ``visualize_size`` in ``customizable_properties``. I am using MATRX version 2.2.0 btw.

**Comment by jwaa** [comment]
> This returns the following error:

Ah, that is too bad. It seems there is a bug there. A workaround is to add the `visualize_size` property when you make the agent with the `WorldBuilder` with the original size as value. No guarantees that this will work though. I made #330 to fix it and with a more detailed description why it fails.

> When adding the agent using `builder.add_agent`, I included `visualize_size` in `customizable_properties`. I am using MATRX version 2.2.0 btw.

Also good to know. The past few hotfixes did altered the property mechanism, so it might be worthwhile to upgrade and test it with a newer version.

**Comment by jwaa** [comment]
@rsverhagen94 I wrote a solution for MATRX [here](https://github.com/matrx-software/matrx/issues/330#issuecomment-1305944939), although it is a hacky one you could try and see if it fixes it for you. Alternatively, you can wait until we implemented a hotfix and update your MATRX version. 

As a side note; size needs to be an integer as it is a multitude of a grid square :)
